module.exports = {
  GET_POSTS: "GET_POSTS",
  GET_POST: "GET_POST",
  ADD_POST: "ADD_POST",
  DELETE_POST: "DELETE_POST",

  GET_USER: "GET_USER",
  AUTH_SIGN_UP: "AUTH_SIGN_UP",
  AUTH_SIGN_OUT: "AUTH_SIGN_OUT",
  AUTH_SIGN_IN: "AUTH_SIGN_IN",
  AUTH_ERROR: "AUTH_ERROR",
  DASHBOARD_GET_DATA: "DASHBOARD_GET_DATA"
};
